name: Playwright Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install system dependencies for Playwright
        run: |
          sudo apt update
          sudo apt install -y libnss3 libxss1 \
              libasound2tss alsa-utils \
              libatk1.0-0 libcups2 libxcomposite1 libxdamage1 \
              libxrandr2 libgbm1 libpango1.0-0 \
              libffi8 libx264-dev libx11-6 libxext6 libxrender1 libxinerama1 \
              fonts-liberation fonts-liberation2 fonts-dejavu

      - name: Install Node.js dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test --reporter=list
